FROM phpdockerio/php80-fpm:latest
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=nointeractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install php8.0-xdebug php8.0-mysql php8.0-bcmath php8.0-intl \
    && apt-get clean; rm -rf /var/lib/abt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Install git
RUN apt-get update \
    && apt-get -y install git \
    && apt-get clean; rm -rf /var/lib/abt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
