version: '3'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./docker/db.env
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /application
    ports:
      - "8080:80"
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: docker/php
    container_name: php8
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
