version: '3'

services:
  db:
    image: mysql:8.0.23
    container_name: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - ./db.env
    networks:
      - symfony
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: php
    volumes:
      - symfony_dockerized_app_sync:/var/www/symfony
    networks:
      - symfony
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - symfony_dockerized_app_sync:/var/www/symfony
    networks:
      - symfony
    env_file:
      - .env.nginx.local
volumes:
  symfony_dockerized_app_sync:
    external: true
  mysql_data:
networks:
  symfony:
